### ISSUE TITLE
key_sort for get_forecast_daily_volumes

### ISSUE THREAD

**Issue by rsjamesmro** [petbox-dev/combocurve-api-helper#1]
The two functions: get_forecast_daily_volumes and get_forecast_monthly_volumes don't work with the key_sort as the sort columns aren't exposed in the json response.  Unless I'm implementing something incorrectly.

**Comment by dsfulf** [comment]
I've fixed this in `main` (https://github.com/petbox-dev/combocurve-api-helper/commit/b3befc65e8b2171e361861c5e68bc323e3785eca) and `develop` (https://github.com/petbox-dev/combocurve-api-helper/commit/db11b421d8f35e063fcb488f87d2cbd490e8a4d2)

`develop` still has some work to be done to document everything, but I would suggest switching to it for the time being until the official release! It has a lot more features and bugfixes.
